"""add tournament details

Revision ID: 50b91ef0edc0
Revises: 392e22a7fa38
Create Date: 2026-09-12 21:47:16.285667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b91ef0edc0'
down_revision: Union[str, Sequence[str], None] = '392e22a7fa38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('format', sa.String(length=255), nullable=True))
    op.add_column('tournaments', sa.Column('location', sa.String(length=500), nullable=True))
    op.add_column('tournaments', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.add_column('tournaments', sa.Column('rules', sa.Text(), nullable=True))
    op.add_column('tournaments', sa.Column('prize_info', sa.Text(), nullable=True))
    op.add_column('tournaments', sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'registration_deadline')
    op.drop_column('tournaments', 'prize_info')
    op.drop_column('tournaments', 'rules')
    op.drop_column('tournaments', 'image_url')
    op.drop_column('tournaments', 'location')
    op.drop_column('tournaments', 'format')
    # ### end Alembic commands ###
